### ISSUE TITLE
"Unknown" board type crashes OATControl

### ISSUE THREAD

**Issue by hexafluoride** [OpenAstroTech/OpenAstroTracker-Firmware#105]
An "Unknown" board is not handled properly by [Mount::getMountHardwareInfo()](https://github.com/OpenAstroTech/OpenAstroTracker-Firmware/blob/f43939a873d8a12b2d2c2a7799cbcd004b9dab19/src/Mount.cpp#L968): ESP32 and m2560p boards have a trailing comma whereas the Unknown board type does not. This results in the following hardware line being sent by the firmware:

    [00:00:07.560] [06]: Mount: Hardware is UnknownNEMA|20|400,NEMA|20|400,NO_GPS,NO_AZ_ALT,NO_GYRO,NO_LCD,NO_FOC,

causing OATControl to crash, as the missing comma relocates the line segments parsed [here](https://github.com/OpenAstroTech/OpenAstroTracker-Desktop/blob/727b6d65104716c4c550f8ba43166cd8ac5ce21f/OATControl/ViewModels/MountVM.cs#L1393).

**Comment by julianneswinoga** [comment]
Closed with #106
