### ISSUE TITLE
Problems with the focuser

### ISSUE THREAD

**Issue by lfpaca** [OpenAstroTech/OpenAstroTracker-Firmware#140]
Hello all,

I know the focuser is a new addition and not yet fully functional, but I just want to raise a couple of things I noticed.

1. The FOCUS_IN1_PIN for the driver ULN2003 is set as 66 (the same pin used for the ALT_IN1_PIN). I believe it should be 12 (?);
2. The focuser does not work under Ekos and/or N.I.N.A. I believe there is a bug which crashes the focuser function when you try to adjust the rate. Using the display I can move the stepper flawlessly without touching the rate. Once I change it, it stops working and I need to reset the device.

Thanks for the amazing equipment you guys put together.

**Comment by ClutchplateDude** [comment]
Sorry, I didn't even see this until today. Looks like pin 66 is not the right pin.... Not sure what would work, all of us are using NEMAs....
As to your second point, if you could hop on our Discord server and post some logfiles from NINA and ASCOM, we might be able to figure out what's happening.

**Comment by andre-stefanov** [comment]
Closing due to lack of updates on this one.
@lfpaca did you figure it out? is there still an issue? Feel free to comment so we can reopen this issue.
