### ISSUE TITLE
Add a Define so the end user can select whether the mount starts tracking on Power up or imitated by User 

### ISSUE THREAD

**Issue by hdphilip** [OpenAstroTech/OpenAstroTracker-Firmware#150]
Currently, when power is applied to the mount it starts Tracking,  which in many cases that would work the best. But if  the unit is unattended and Parked , and a power glitch were to occur, the Oat would reset and start to track without guidance.  
the statement would be like   #define  AUTOTRACKING  ON POWER ON   True or  False  of course the default would be True,  to continue on how it is already setup, but the False would give the operator an option for tracking on power up.

**Comment by andre-stefanov** [comment]
Hi @hdphilip, thx for this feedback. We discussed it shortly in team and find it a very reasonable enhancement. We will take a look into it.
