### ISSUE TITLE
Wrong Longitude parsing offset.

### ISSUE THREAD

**Issue by anjok** [OpenAstroTech/OpenAstroTracker-Firmware#166]
Apparently there's a 180 deg offset considered when parsing the longitude which is not actually sent, at least not from KStars. KStars simply sends "-11.4" when you're at "11.4" which what's expected from the Meade spec.

Please remove that offset so that LST and HA can be calculated correctly.

You might need to fix the ASCOM driver too and tell all users to upgrade or send the version of the driver in a special command and either add or not add the offset.

**Comment by JakobPetersson** [comment]
Fixes for this are included in #181.
