### ISSUE TITLE
Problems creating a working config for mega2500 L293 Motorshield 

### ISSUE THREAD

**Issue by Thrillerninja** [OpenAstroTech/OpenAstroTracker-Firmware#186]
Hi, is there any guide how to create a config by yourself, or even a finished config for using a [L293](https://elektro.turanis.de/html/prj144/index.html) Motor Shield? I have big problems figuring out where to change stuff needed to get it working

**Comment by julianneswinoga** [comment]
Since the L293 uses a shift register to interface with the microcontroller it is incompatible with our stepper library (which needs direct access to step and direction pins). Sorry :frowning_face:

**Comment by Thrillerninja** [comment]
How difficult do you think it would be to change the Stepper lib?

**Comment by julianneswinoga** [comment]
You can check it out yourself, _most_ of the stepper code is in `src/Mount.cpp` and it's not very well abstracted. It would be a lot of work just to support an obscure piece of HW for one person :grin:

**Comment by Thrillerninja** [comment]
Yeah, but going to look into it. Thanks for the help
