### ISSUE TITLE
Nema17, Generic driver, Not tracking

### ISSUE THREAD

**Issue by waynoedm** [OpenAstroTech/OpenAstroTracker-Firmware#19]
New build. Running Mega2560, LCD+kaypad. Nema17 w/ A4988 drivers on RA and DEC. Running 1.8.53. Updated to 1.8.64. 

Prior to update, RA tracked no problem. After update, will not track. Can skew RA and DEC no issues. Just does not track. Track stepper counter increases.

**Comment by CTetford** [comment]
Is this still an issue on the latest firmware?

**Comment by waynoedm** [comment]
No. Mind you, this latest setup is running different drivers (Trinamic).
I'll update my other setup and give it a try.

**Comment by CTetford** [comment]
There were issues with A4988 drivers that recently got resolved in v1.10.6. Closing this issue, please re-open if the issue persists with the latest firmware.
