### ISSUE TITLE
unable to download

### ISSUE THREAD

**Issue by strutdevil** [OpenAstroTech/OpenAstroTracker-Firmware#194]
I open the .ino in arduino and follow the directions. When i hit ctrl u it gives me this error. I'm not sure what I am doing wrong.

C:\Users\Chris\AppData\Local\Temp\cckK8d9i.ltrans0.ltrans.o: In function `main':
C:\Users\Chris\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.5\cores\arduino/main.cpp:43: undefined reference to `setup'
C:\Users\Chris\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.5\cores\arduino/main.cpp:46: undefined reference to `loop'
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

**Comment by julianneswinoga** [comment]
Hi, could you try using a new tool we're working on to compile + upload the firmware?
https://github.com/OpenAstroTech/OATFWGUI/releases/tag/0.0.9
It's in pre-release right now but it's intended to solve exactly problems like this for new users.

It it doesn't work, no worries we'll circle back to your Arduino IDE problem.

**Comment by strutdevil** [comment]
I tried the new link. Didn't seem to matter what options I chose in the menu it had different errors. I'm assuming since uno wasn't an option that may be the problem or I'm just to new. Thank you for trying.

**Comment by julianneswinoga** [comment]
Could you upload the log with the errors? Should be in the `logs` directory where you ran the executable. But also yes, the Uno is not supported (not enough memory to run the firmware)

**Comment by strutdevil** [comment]
I deleted everything after getting frustrated. I'll try again when I have some time. I only need it to run 1 stepper at sidereal rate and then return to home on a dobsonian equatorial platform so this may be overkill.

**Comment by julianneswinoga** [comment]
Yeah sorry to hear that, the OAT Firmware is only really meant for a full EQ setup on OAT-like hardware.
Maybe something like [OnStep](https://onstep.groups.io/g/main/wiki/Home) is more what you're looking for?
