### ISSUE TITLE
Steppers Speed

### ISSUE THREAD

**Issue by edombek** [OpenAstroTech/OpenAstroTracker-Firmware#224]
changing *_STEPPER_SPEED brings no response. I find defines speed and  see that they are set through microsteps... *_STEPPER_SPEED used ONLY for UART testing... Why?

**Comment by ClutchplateDude** [comment]
What firmware version?

**Comment by ClutchplateDude** [comment]
This is really not suited for a Github issue, but better for Discord discussion….
