### ISSUE TITLE
Dynamic Motor Torque Control

### ISSUE THREAD

**Issue by CTetford** [OpenAstroTech/OpenAstroTracker-Firmware#33]
Using UART to read the StallGuard4 SG_RESULT register the motor load can be measured.

The motor RMS current can be dynamically adjusted on-the-fly to lower power draw, and ramp up as required.

This way the OAT saves on battery usage.

See Section 11 of the TMC2209 datasheet:
https://www.trinamic.com/fileadmin/assets/Products/ICs_Documents/TMC2209_Datasheet_V103.pdf

**Comment by andre-stefanov** [comment]
@CTetford i think this one can be closed?

**Comment by CTetford** [comment]
Yes, especially considering your preliminary results of microstepping accuracy
