### ISSUE TITLE
ESP32 AP Mode

### ISSUE THREAD

**Issue by red-gee** [OpenAstroTech/OpenAstroTracker-Firmware#35]
i have some trouble to get the ESP32 config to work with Skysafari on iOS.

every time, when I connect the ESP with the iPhone the Esp gets into panic and reboot. 

does anyone have a working config file, I could test?

**Comment by ClutchplateDude** [comment]
Please don't open issues because you are having trouble getting things to work. That is what our Reddit or Slack support is for. GitHub issues are for actual source code issues that you find.
