### ISSUE TITLE
"default_envs" in platormio.ini is commented out

### ISSUE THREAD

**Issue by waynoedm** [OpenAstroTech/OpenAstroTracker-Firmware#71]
Coming up as:
`[platformio]
; default_envs = mega2560`

Causing it to compile all platforms.

**Comment by andre-stefanov** [comment]
Yes this was on intent. If someone needs a specific environment, he can chose it in PIO IDE. having default to build all is useful for devs to quickly check if all environments are still building. Is it causing some issues for you?

**Comment by waynoedm** [comment]
No problems. It was just was not expected so it wasn't clear that it was intentional.
